CREATE DATABASE IF NOT EXISTS demo_fees;
USE demo_fees;


CREATE TABLE IF NOT EXISTS admins (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(150) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS students (
id INT AUTO_INCREMENT PRIMARY KEY,
usn VARCHAR(50) UNIQUE,
name VARCHAR(150),
branch VARCHAR(100),
year VARCHAR(20),
email VARCHAR(150),
password VARCHAR(255),
fee_amount DECIMAL(10,2) DEFAULT 0,
due_date DATE NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS payments (
id INT AUTO_INCREMENT PRIMARY KEY,
student_id INT,
razorpay_order_id VARCHAR(200),
razorpay_payment_id VARCHAR(200),
amount DECIMAL(10,2) DEFAULT 0,
status VARCHAR(50) DEFAULT 'created',
paid_at TIMESTAMP NULL DEFAULT NULL,
receipt VARCHAR(200) DEFAULT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS notifications (
id INT AUTO_INCREMENT PRIMARY KEY,
student_id INT NULL,
title VARCHAR(255),
message TEXT,
is_read TINYINT(1) DEFAULT 0,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE SET NULL
);